version: 2
jobs:
    build:
        docker:
            - image: circleci/python
        steps:
            - checkout
            - run:
                  name: Clean Repo
                  command: 'rm -rf public'
            - run:
                  name: Build Site
                  command: './tools/hugo-linux'

    artifact:
        docker:
            - image: circleci/python
        steps:
            - store_artifacts:
                  path: ./public

    # deploy:
    #     docker:
    #         - image: circleci/python
    #     steps:
    #         - run:
    #               name: Install awscli
    #               command: sudo pip install awscli
    #         - run:
    #               name: Deploy to S3
    #               command: aws s3 sync public s3://$BUCKET_URL

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - artifact:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
            # - deploy:
            #       requires:
            #           - build
            #       filters:
            #           branches:
            #               only: master
