version: 2
jobs:
    build:
        docker:
            - image: mesosphere/aws-cli
        steps:
            - checkout
            - run:
                  name: Clean Repo
                  command: 'rm -rf public'
            - run:
                  name: Build Site
                  command: './tools/hugo-linux'
            - persist_to_workspace:
                  root: public
                  paths:
                      - ./*

    artifact:
        docker:
            - image: mesosphere/aws-cli
        steps:
            - attach_workspace:
                  at: public
            - store_artifacts:
                  path: ./public

    deploy:
        docker:
            - image: mesosphere/aws-cli
        steps:
            - attach_workspace:
                  at: public
            - run:
                  name: Deploy to S3
                  command: aws s3 sync public s3://anderc.com.s3-website-us-east-1.amazonaws.com

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - artifact:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
            - deploy:
                  requires:
                      - build
                      - artifact
                  filters:
                      branches:
                          only: master
#TODO: CRA cache things and make better
#TODO: CRA Pull from github
#TODO: CRA Set up domain for anderc.com and test deploy.
