# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Cloudflare

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "cloudflare"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build_deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Make Hugo Executable
        run: chmod +x hugo-linux
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          ./hugo-linux \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Cloudflare Pages GitHub Action
        # You may pin to the exact commit or the version.
        # uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca
        uses: cloudflare/pages-action@v1.5.0
        with:
          # Cloudflare API Token
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # Cloudflare Account ID
          accountId: ${{ secrets.CF_ACCT_ID }}
          # The name of the Pages project to upload to
          projectName: anderc-com
          # The directory of static assets to upload
          directory: public
